(define (problem sysadmin-5)
	(:domain sysadmin)
	(:objects comp0 comp1 comp2 comp3 comp4 - comp)
(:init 	(conn comp0 comp1)
		(conn comp1 comp2)
		(conn comp2 comp3)
		(conn comp3 comp4)
		(conn comp4 comp0)
		(conn comp3 comp2)
		(conn comp0 comp4)
)
(:goal (and (up comp0) (up comp1) (up comp2) (up comp3) (up comp4)))
)