name: build
on: [push, pull_request]
jobs:
  test:
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, '3.10', 3.11]
      fail-fast: false
    name: Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    # Tests
    - run: python test_parser.py
    #- run: python test_planner.py
    # Examples
    - run: python ippddl_parser/action.py
    - run: python -m ippddl_parser.parser examples/dinner/dinner.pddl examples/dinner/pb1.pddl
    #- run: python -m ippddl_parser.planner examples/dinner/dinner.pddl examples/dinner/pb1.pddl